server:
  port: 9092

peer1:
  name: peer1
  address: 127.0.0.2
  port: 8762
  
peer2:
  name: peer2
  address: 127.0.0.3
  port: 8763 
  
peer3:
  name: peer3
  address: 127.0.0.4
  port: 8764

eureka:
  client:
    serviceUrl:
      defaultZone: http://${peer1.address}:${peer1.port}/eureka/,http://${peer2.address}:${peer2.port}/eureka/,http://${peer3.address}:${peer3.port}/eureka/
      #defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/,http://peer3:8764/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: test-service