spring:
  profiles: default
server:
  port: 8761  
eureka:
  environment: local
  instance:
    hostname: localhost #default-eureka
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/    
 
---
spring:
  profiles: peer1
  application:
    name: eureka-clustered
server:
  port: 8762  
eureka:
  environment: local
  instance:
    securePortEnabled: true
    hostname: peer-1 
  client:
    registerWithEureka: false
    fetchRegistry: false       
    serviceUrl:
      defaultZone: http://peer2:8763/eureka/,http://peer3:8764/eureka/
 
---
spring:
  profiles: peer2
  application:
    name: eureka-clustered   
server:
  port: 8763
eureka:
  environment: local
  instance:
    securePortEnabled: true
    hostname: peer2      
  client:
    registerWithEureka: false
    fetchRegistry: false       
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer3:8764/eureka/
 
---
spring:
  profiles: peer3
  application:
    name: eureka-clustered  
server:
  port: 8764
eureka:
  environment: local
  instance:
    securePortEnabled: true
    hostname: peer3    
  client:
    registerWithEureka: false
    fetchRegistry: false   
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/