server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/,http://peer2:8763/eureka/,http://peer3:8764/eureka/
    healthcheck:
      enabled: true

spring:
  application:
    name: node-service